// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildGraph(arg1, arg2) {
  return window['go']['main']['App']['BuildGraph'](arg1, arg2);
}

export function BuildGraphFromSelected(arg1, arg2) {
  return window['go']['main']['App']['BuildGraphFromSelected'](arg1, arg2);
}

export function CancelBuild() {
  return window['go']['main']['App']['CancelBuild']();
}

export function CancelOAuth() {
  return window['go']['main']['App']['CancelOAuth']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function FetchFollowList(arg1) {
  return window['go']['main']['App']['FetchFollowList'](arg1);
}

export function FetchFollowListForUsers(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchFollowListForUsers'](arg1, arg2, arg3);
}

export function FindMutualFollows(arg1) {
  return window['go']['main']['App']['FindMutualFollows'](arg1);
}

export function FindMutualFollowsBetween(arg1, arg2) {
  return window['go']['main']['App']['FindMutualFollowsBetween'](arg1, arg2);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetGraphStats(arg1) {
  return window['go']['main']['App']['GetGraphStats'](arg1);
}

export function GetRateLimitInfo() {
  return window['go']['main']['App']['GetRateLimitInfo']();
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PollOAuthOnce() {
  return window['go']['main']['App']['PollOAuthOnce']();
}

export function SetToken(arg1) {
  return window['go']['main']['App']['SetToken'](arg1);
}

export function StartDeviceFlow() {
  return window['go']['main']['App']['StartDeviceFlow']();
}
