// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graph} from '../models';
import {main} from '../models';
import {github} from '../models';

export function BuildGraph(arg1:string,arg2:number):Promise<graph.Graph>;

export function BuildGraphFromSelected(arg1:string,arg2:Record<number, Array<string>>):Promise<graph.Graph>;

export function CancelBuild():Promise<void>;

export function CancelOAuth():Promise<void>;

export function ClearCache():Promise<void>;

export function FetchFollowList(arg1:string):Promise<graph.FollowListResult>;

export function FetchFollowListForUsers(arg1:Array<string>,arg2:Array<string>,arg3:number):Promise<graph.FollowListResult>;

export function FindMutualFollows(arg1:graph.Graph):Promise<Array<graph.Edge>>;

export function FindMutualFollowsBetween(arg1:string,arg2:string):Promise<graph.MutualFollowResult>;

export function GetAuthStatus():Promise<main.AuthStatus>;

export function GetGraphStats(arg1:graph.Graph):Promise<graph.GraphStats>;

export function GetRateLimitInfo():Promise<main.RateLimitInfo>;

export function GetUser(arg1:string):Promise<graph.UserNode>;

export function Logout():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PollOAuthOnce():Promise<main.OAuthPollResult>;

export function SetToken(arg1:string):Promise<void>;

export function StartDeviceFlow():Promise<github.DeviceFlowResult>;
